version: '3.8'

services:
  sunoapi_dev:
    container_name: musicdata_sunoapi_dev
    build:
      context: ./suno-api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./suno-api:/usr/src/app/suno-api

  backend_dev:
    container_name: musicdata_backend_dev
    build:
      context: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/usr/src/app/backend
      - /var/run/docker.sock:/var/run/docker.sock
      - ./suno-api:/usr/src/app/suno-api
      - ./frontend:/usr/src/app/frontend
      - ./docker-compose.dev.yml:/usr/src/app/docker-compose.yml
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - FASTAPI_ENV=development
      - SUNOAPI_BASE_URL=http://sunoapi_dev:3000
      - PROJ_COMPOSE=/usr/src/app/docker-compose.yml

  frontend_dev:
    container_name: musicdata_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./docker-compose.dev.yml:/usr/src/app/docker-compose.yml
    environment:
      - NODE_ENV=dev
    depends_on:
      - backend_dev
      - sunoapi_dev

networks:
  default:
    name: musicdata_dev_network
